// <auto-generated />
using System;
using API_Simulacao_Hack.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_Simulacao_Hack.Migrations
{
    [DbContext(typeof(SimulacaoContext))]
    [Migration("20250824173901_AdicaoTipoSimulacaoRota")]
    partial class AdicaoTipoSimulacaoRota
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("API_Simulacao_Hack.Models.Simulacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int>("CodigoProduto")
                        .HasColumnType("int")
                        .HasColumnName("codigoProduto");

                    b.Property<DateOnly>("DataReferencia")
                        .HasColumnType("TEXT")
                        .HasColumnName("dataReferencia");

                    b.Property<string>("DescricaoProduto")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("descricaoProduto");

                    b.Property<int>("IdSimulacao")
                        .HasColumnType("integer")
                        .HasColumnName("idSimulacao");

                    b.Property<int>("Prazo")
                        .HasColumnType("int")
                        .HasColumnName("prazo");

                    b.Property<decimal>("TaxaJuros")
                        .HasColumnType("decimal(10,9)")
                        .HasColumnName("taxaJuros");

                    b.Property<string>("TipoSimulacao")
                        .IsRequired()
                        .HasColumnType("varchar(5)")
                        .HasColumnName("tipoSimulacao");

                    b.Property<decimal>("ValorDesejado")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valorDesejado");

                    b.Property<decimal>("ValorMediaPrestacoes")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valorMediaPrestacoes");

                    b.Property<decimal>("ValorTotalParcelas")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valorTotalParcelas");

                    b.HasKey("Id");

                    b.ToTable("Simulacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
